"""
VIP Medical Group lease checklist — all 60+ items embedded for GPT-4 prompts.
"""

CHECKLIST_ITEMS = [
    {"section": "Entity Name", "what_to_look_for": "Legal entity name used as Tenant throughout the lease", "vip_standard": "Tenant must be identified as 'National VIP Centers Management LLC'", "red_flag": "Any other entity name used (e.g., 'VIP Medical Group', 'Dr. Caroline Novak', individual name, or any other variation)", "priority": "High"},
    {"section": "Commencement Date", "what_to_look_for": "Trigger methodology", "vip_standard": "Commencement upon Substantial Completion (SC)", "red_flag": "Commencement BEFORE SC", "priority": "High"},
    {"section": "Rent Commencement", "what_to_look_for": "When rent begins", "vip_standard": "Rent begins AFTER SC + abatement period", "red_flag": "Rent due before SC", "priority": "High"},
    {"section": "Substantial Completion Definition", "what_to_look_for": "Detailed SC definition", "vip_standard": "SC = all LL work complete except punch list", "red_flag": "SC includes unfinished major items", "priority": "High"},
    {"section": "Punch List Timing", "what_to_look_for": "Duration and obligations", "vip_standard": "LL completes punch list within 30 days", "red_flag": "No deadline or >45 days", "priority": "Medium"},
    {"section": "Tenant Delay", "what_to_look_for": "Definition and notice requirement", "vip_standard": "Tenant delay only counts if LL issues written notice first", "red_flag": "LL can declare arbitrarily", "priority": "Medium"},
    {"section": "Delivery Condition", "what_to_look_for": "Base building condition at delivery", "vip_standard": "Delivered broom clean + HVAC/electrical/plumbing in good working order", "red_flag": "Delivered AS-IS with no warranties", "priority": "High"},
    {"section": "HVAC – Repair Responsibility", "what_to_look_for": "Who handles repairs?", "vip_standard": "LL responsible for all HVAC repairs", "red_flag": "Tenant responsible for all repairs", "priority": "Medium"},
    {"section": "HVAC – Replacement Responsibility", "what_to_look_for": "Who pays for replacement?", "vip_standard": "LL responsible for HVAC replacement", "red_flag": "Tenant full replacement responsibility", "priority": "Medium"},
    {"section": "HVAC – Age Disclosure", "what_to_look_for": "LL disclosure of HVAC age/condition", "vip_standard": "LL provides age, maintenance records, and warranty info", "red_flag": "No disclosure whatsoever", "priority": "Low"},
    {"section": "HVAC – Warranty", "what_to_look_for": "LL warranty period on HVAC", "vip_standard": "LL warranties HVAC for 12 months minimum", "red_flag": "No warranty", "priority": "Low"},
    {"section": "Roof", "what_to_look_for": "Maintenance and repair responsibility", "vip_standard": "LL responsible for roof", "red_flag": "Tenant responsible", "priority": "Medium"},
    {"section": "Fire Sprinkler System", "what_to_look_for": "Maintenance responsibility", "vip_standard": "LL responsible for fire sprinkler system", "red_flag": "Tenant responsible", "priority": "Medium"},
    {"section": "Electrical Capacity", "what_to_look_for": "Capacity adequate for medical equipment (ultrasound, exam chairs, IT)", "vip_standard": "Verified electrical capacity for medical office use (does NOT need to be 'medical grade' — we do not use continuous-use equipment like ventilators)", "red_flag": "Tenant must upgrade electrical at own cost", "priority": "High"},
    {"section": "Water Supply", "what_to_look_for": "Adequate water for sinks and sterilization", "vip_standard": "LL confirms adequate water supply and capacity", "red_flag": "Tenant must install booster pump at own cost", "priority": "Medium"},
    {"section": "Use Clause", "what_to_look_for": "Is medical use explicitly permitted?", "vip_standard": "Medical office and related uses permitted without restriction", "red_flag": "Limited use clause or LL won't guarantee zoning for medical", "priority": "High"},
    {"section": "Zoning Guarantee", "what_to_look_for": "LL representation on zoning", "vip_standard": "LL confirms zoning permits medical office use", "red_flag": "Tenant must verify zoning at own risk", "priority": "High"},
    {"section": "Exclusivity", "what_to_look_for": "Competing uses in the building or center", "vip_standard": "Exclusive use clause for vein/interventional radiology", "red_flag": "No exclusivity protection at all", "priority": "Low"},
    {"section": "Operating Expenses (OPEX) Cap", "what_to_look_for": "Cap structure and mechanics", "vip_standard": "4–5% non-compounding, non-cumulative annual cap", "red_flag": "Uncapped OPEX", "priority": "Medium"},
    {"section": "Operating Expense Definition", "what_to_look_for": "Clarity and exclusions from OPEX", "vip_standard": "Clear exclusions: capital costs, LL legal fees, depreciation, LL profit", "red_flag": "Broad LL discretion to include anything in OPEX", "priority": "Medium"},
    {"section": "Base Year", "what_to_look_for": "Base year setup for OPEX calculations", "vip_standard": "Base year = next full calendar year after commencement", "red_flag": "Manipulated or artificially low base year", "priority": "Medium"},
    {"section": "Proportionate Share", "what_to_look_for": "Fixed or variable?", "vip_standard": "Fixed proportionate share for the full lease term", "red_flag": "LL can remeasure and adjust at any time", "priority": "Medium"},
    {"section": "Janitorial", "what_to_look_for": "Responsibility for janitorial services", "vip_standard": "Tenant handles interior janitorial only", "red_flag": "LL requires exclusive vendor at tenant's expense", "priority": "Low"},
    {"section": "Trash Removal", "what_to_look_for": "Cost and responsibility", "vip_standard": "Trash removal included in OPEX", "red_flag": "Tenant must arrange and pay privately", "priority": "Medium"},
    {"section": "TI Allowance", "what_to_look_for": "Dollar amount of tenant improvement allowance", "vip_standard": "$100–$130 per RSF (assuming market rent and 10-year term; lower if rent or term is below market)", "red_flag": "Less than $85 per RSF", "priority": "Medium"},
    {"section": "TI Disbursement", "what_to_look_for": "How TI funds are released", "vip_standard": "Preference: LL performs work and pays contractor directly. If TI reimbursement: progress draws with 10% retainage.", "red_flag": "Reimbursement only at project completion", "priority": "Medium"},
    {"section": "TI Expiration Deadline", "what_to_look_for": "How long tenant has to use TI", "vip_standard": "18–24 months minimum", "red_flag": "Less than 12 months (though less critical if rent starts at SC)", "priority": "Medium"},
    {"section": "Modifications and Buildout", "what_to_look_for": "Who performs the buildout?", "vip_standard": "LL performs all work and is wholly responsible", "red_flag": "Tenant required to perform buildout work", "priority": "High"},
    {"section": "TI Change Orders", "what_to_look_for": "Approval process for change orders", "vip_standard": "LL cannot unreasonably withhold approval of change orders", "red_flag": "LL charges excessive fees for change orders", "priority": "Medium"},
    {"section": "Construction Management Fee", "what_to_look_for": "LL construction management fee", "vip_standard": "0–3% CM fee", "red_flag": "Greater than 5% AND deducted from TI allowance", "priority": "Medium"},
    {"section": "Permits", "what_to_look_for": "Who is responsible for building permits?", "vip_standard": "LL responsible for all required building permits", "red_flag": "Tenant responsible for permits at own cost", "priority": "High"},
    {"section": "SC Trigger", "what_to_look_for": "Objective vs. subjective SC trigger", "vip_standard": "Objective checklist-based SC trigger", "red_flag": "LL has sole subjective discretion to declare SC", "priority": "High"},
    {"section": "Holdover Rent", "what_to_look_for": "Holdover rental rate", "vip_standard": "100–120% of base rent during holdover", "red_flag": "200% or more of base rent", "priority": "Low"},
    {"section": "Security Deposit", "what_to_look_for": "Amount required", "vip_standard": "1–2 months rent", "red_flag": "More than 3 months or tied to gross annual rent", "priority": "Medium"},
    {"section": "Personal Guaranty", "what_to_look_for": "Personal guaranty required?", "vip_standard": "No personal guaranty required", "red_flag": "Full personal guaranty required", "priority": "High"},
    {"section": "Parking Ratio", "what_to_look_for": "Parking availability", "vip_standard": "Pro-rata parking included at no additional cost", "red_flag": "Insufficient stalls or paid reserved parking only", "priority": "Medium"},
    {"section": "Reserved Parking", "what_to_look_for": "Reserved spaces available?", "vip_standard": "1–2 reserved spaces optional", "red_flag": "No reserved parking allowed at all", "priority": "Medium"},
    {"section": "Signage – Door", "what_to_look_for": "Door signage rights", "vip_standard": "Door signage included at no extra cost", "red_flag": "LL highly restrictive on door signage", "priority": "High"},
    {"section": "Signage – Directory", "what_to_look_for": "Building directory listing", "vip_standard": "Directory listing included at no extra cost", "red_flag": "No directory listing allowed", "priority": "High"},
    {"section": "Signage – Monument", "what_to_look_for": "Monument sign panel available?", "vip_standard": "Monument panel available (fee acceptable)", "red_flag": "No monument rights available", "priority": "High"},
    {"section": "Building-Mounted Signs", "what_to_look_for": "Exterior building signage", "vip_standard": "Allowed subject to applicable code", "red_flag": "Not a deal-breaker but note any restrictions", "priority": "Medium"},
    {"section": "After-Hours HVAC", "what_to_look_for": "After-hours HVAC rate and availability", "vip_standard": "$20–$40/hr; not an issue if standard HVAC hours match or are within 1 hour of our business hours", "red_flag": "Excessive rate over $60/hr, especially if HVAC hours are well outside our business hours", "priority": "Medium"},
    {"section": "Electricity", "what_to_look_for": "How electricity is billed", "vip_standard": "Included in OPEX or separately metered fairly", "red_flag": "Flat rate without cost disclosure", "priority": "Low"},
    {"section": "Relocation Clause", "what_to_look_for": "Can LL force tenant to relocate?", "vip_standard": "No relocation clause permitted", "red_flag": "LL can relocate tenant without consent", "priority": "High"},
    {"section": "LL Access", "what_to_look_for": "Notice required before entry", "vip_standard": "24–48 hours advance notice except genuine emergencies", "red_flag": "LL can enter at any time without notice", "priority": "Medium"},
    {"section": "Quiet Enjoyment", "what_to_look_for": "Quiet enjoyment protection for tenant", "vip_standard": "Strong quiet enjoyment covenant in lease", "red_flag": "Weak or missing quiet enjoyment protection", "priority": "Medium"},
    {"section": "Insurance – Tenant", "what_to_look_for": "Required tenant insurance limits", "vip_standard": "Reasonable limits appropriate for medical office", "red_flag": "Excessively high limits", "priority": "High"},
    {"section": "Insurance – LL", "what_to_look_for": "LL insurance obligations", "vip_standard": "LL maintains building and property insurance", "red_flag": "LL pushes building insurance costs to tenant", "priority": "Medium"},
    {"section": "Indemnity", "what_to_look_for": "Indemnity structure", "vip_standard": "Mutual and negligence-based indemnity", "red_flag": "Broad unilateral tenant indemnity", "priority": "Medium"},
    {"section": "SNDA", "what_to_look_for": "Subordination, Non-Disturbance and Attornment", "vip_standard": "LL provides SNDA protecting tenant", "red_flag": "No SNDA available", "priority": "Low"},
    {"section": "Estoppel Certificates", "what_to_look_for": "Frequency of estoppel demands", "vip_standard": "Standard — once per year maximum", "red_flag": "Uncapped estoppel demands", "priority": "Medium"},
    {"section": "Default + Cure Periods", "what_to_look_for": "Grace periods for defaults", "vip_standard": "5–10 days for rent default; 30 days for other defaults", "red_flag": "Immediate default with no cure period", "priority": "Medium"},
    {"section": "Late Fees", "what_to_look_for": "Late fee amount", "vip_standard": "Less than 5%", "red_flag": "Greater than 8%", "priority": "Low"},
    {"section": "Rent Payment Method", "what_to_look_for": "ACH/wire accepted?", "vip_standard": "ACH payment required/accepted", "red_flag": "Certified check only — no electronic payment", "priority": "Medium"},
    {"section": "Surrender", "what_to_look_for": "Surrender condition at lease end", "vip_standard": "Broom clean + remove only specialty items", "red_flag": "Remove all improvements at tenant's cost", "priority": "High"},
    {"section": "Restoration", "what_to_look_for": "Restoration obligations", "vip_standard": "LL cannot require restoration unless truly specialty items", "red_flag": "LL requires full restoration of all improvements", "priority": "High"},
    {"section": "LL Work Letter", "what_to_look_for": "Detail and scope of work letter", "vip_standard": "Detailed scope of work with timeline", "red_flag": "Ambiguous or missing work letter", "priority": "High"},
    {"section": "Construction Schedule", "what_to_look_for": "LL construction deadlines", "vip_standard": "Timeline with penalties for LL delays", "red_flag": "No construction timeline at all", "priority": "High"},
    {"section": "As-Builts", "what_to_look_for": "As-built drawings required?", "vip_standard": "LL provides as-built drawings", "red_flag": "LL requires tenant to produce as-builts at own cost", "priority": "High"},
    {"section": "ADA Compliance", "what_to_look_for": "ADA responsibility", "vip_standard": "LL responsible for base building ADA compliance", "red_flag": "Tenant responsible for full ADA compliance", "priority": "High"},
    {"section": "Environmental / Mold", "what_to_look_for": "Environmental and mold responsibility", "vip_standard": "LL responsible for pre-existing environmental issues and mold", "red_flag": "Tenant takes on all environmental liability", "priority": "Medium"},
    {"section": "Roof Leaks", "what_to_look_for": "Roof leak responsibility", "vip_standard": "LL responsible for all roof leak repairs", "red_flag": "Tenant responsible for roof leak damage", "priority": "Medium"},
    {"section": "Plumbing", "what_to_look_for": "Plumbing maintenance", "vip_standard": "LL responsible for main plumbing", "red_flag": "Tenant responsible for all plumbing", "priority": "Medium"},
    {"section": "Elevators", "what_to_look_for": "Elevator maintenance", "vip_standard": "LL maintains elevators", "red_flag": "Tenant responsible for elevator maintenance", "priority": "Medium"},
    {"section": "Telecom Access", "what_to_look_for": "Telecom vendor restrictions", "vip_standard": "Multiple telecom vendors permitted", "red_flag": "Single vendor exclusive — no alternatives", "priority": "Medium"},
    {"section": "Access Control", "what_to_look_for": "Suite access control", "vip_standard": "Tenant controls suite access system", "red_flag": "LL controls all access including tenant suite", "priority": "Medium"},
    {"section": "Generator / Backup Power", "what_to_look_for": "Backup power availability", "vip_standard": "LL confirms building power stability", "red_flag": "No backup power discussion or tenant bears all risk", "priority": "Low"},
]

DEAL_SUMMARY_FIELDS = [
    {"field": "Tenant Entity Name", "vip_standard": "National VIP Centers Management LLC"},
    {"field": "RSF", "vip_standard": "Fixed at lease execution"},
    {"field": "Base Rent (Year 1)", "vip_standard": "Market appropriate / consistent with comps"},
    {"field": "Annual Escalation", "vip_standard": "3% standard"},
    {"field": "Term Length", "vip_standard": "60–120 months"},
    {"field": "Abatement Months", "vip_standard": "3–6 months depending on TI"},
    {"field": "TI Allowance", "vip_standard": "$100–$130 per RSF"},
    {"field": "TI Deadline", "vip_standard": "18–24 months minimum"},
    {"field": "Construction Management Fee", "vip_standard": "0–3%"},
    {"field": "Security Deposit", "vip_standard": "1–2 months"},
    {"field": "Personal Guaranty Required", "vip_standard": "No personal guaranty"},
    {"field": "Commencement Date", "vip_standard": "Upon Substantial Completion"},
    {"field": "Rent Commencement", "vip_standard": "Post-SC + abatement period"},
    {"field": "Operating Expenses Cap", "vip_standard": "4–5% non-cumulative"},
    {"field": "Proportionate Share", "vip_standard": "Fixed for full term"},
    {"field": "Parking", "vip_standard": "Pro-rata free parking included"},
    {"field": "Signage (Door)", "vip_standard": "Included"},
    {"field": "Signage (Directory)", "vip_standard": "Included"},
    {"field": "Signage (Monument)", "vip_standard": "Panel included when available"},
    {"field": "Use Clause", "vip_standard": "Medical office without restriction"},
    {"field": "Zoning Guarantee", "vip_standard": "LL confirms medical use is permitted"},
    {"field": "Relocation Clause", "vip_standard": "Not permitted"},
    {"field": "Holdover Rate", "vip_standard": "100–120%"},
    {"field": "SNDA", "vip_standard": "LL provides"},
]

def build_checklist_text():
    lines = []
    for item in CHECKLIST_ITEMS:
        lines.append(
            f"- {item['section']} [{item['priority']} Priority]: "
            f"Look for: {item['what_to_look_for']}. "
            f"VIP Standard: {item['vip_standard']}. "
            f"Red Flag: {item['red_flag']}."
        )
    return "\n".join(lines)
